import { ThemeProvider } from '../../context/ThemeContext';
import Footer from './components/footer/page';
import Header from './components/header/page';
import './globals.css';

export const metadata = {
  title: 'Just Blog',
  description: 'Generated by create next app',
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className="">
        <ThemeProvider>
          <Header />
          {children}
          <Footer />
        </ThemeProvider>
      </body>
    </html>
  );
}
